# Generated by Django 4.2.4 on 2023-09-28 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_create', models.DateField(default=datetime.date(2023, 9, 28))),
                ('date_of_form', models.DateField(default=datetime.date(2023, 9, 28))),
                ('date_of_finish', models.DateField(default=datetime.date(2023, 9, 28))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expertise.application')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expertise.expertise')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='moderator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expertise.user'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expertise.status'),
        ),
    ]
