# Generated by Django 4.2.4 on 2023-09-28 08:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expertise', '0002_application_user_expapp_application_moderator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_of_create',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_finish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_form',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
