# Generated by Django 4.2.4 on 2024-01-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paintings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.BinaryField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('price', models.CharField(blank=True, null=True)),
                ('context', models.CharField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Expertises',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('formated_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'В работе'), (3, 'Завершена'), (4, 'Отклонена'), (5, 'Удалена')], default=1)),
                ('paintings', models.ManyToManyField(to='painting.paintings')),
            ],
        ),
        migrations.CreateModel(
            name='PaintExps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painting.expertises')),
                ('painting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='painting.paintings')),
            ],
            options={
                'unique_together': {('expertise', 'painting')},
            },
        ),
    ]
