# Generated by Django 4.2.4 on 2024-01-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertises',
            name='artist',
            field=models.CharField(blank=True, null=True),
        ),
    ]
